---
title: "leaflet"
format: html
---


```{r}
leaflet::leaflet()
```


```{r}
leaflet::leaflet() |>
  leaflet::addTiles()
```


```{r}
dados <- abjData::pnud_min
```


```{r}
dados |>
  dplyr::filter(ano == 2010) |>
  dplyr::slice_max(order_by = idhm, n = 10) |>
  leaflet::leaflet() |>
  leaflet::addTiles() |>
  leaflet::addMarkers(
    lng = ~lon,
    lat = ~lat,
    label = ~muni_nm,
    popup = ~ as.character(paste(muni_nm, "<br><br>", "<b>IDHM</b>:", idhm))
  )
```


```{r}
# tab_geo <- geobr::read_state(year = 2020)
# tab_geo |>
#   sf::st_simplify(dTolerance = 200) |>
#   saveRDS("2024-07-22/tab_geo.rds")

tab_geo <- readRDS(here::here("2024-07-22/tab_geo.rds"))
```


```{r}
tab_mapa <- dados |>
  dplyr::group_by(uf_sigla) |>
  dplyr::summarise(
    espvida = mean(espvida, na.rm = TRUE)
  )  |>
  dplyr::right_join(
    tab_geo,
    by = c("uf_sigla" = "abbrev_state")
  ) |>
  sf::st_as_sf() 

color_map <- leaflet::colorBin(
  palette = "YlOrRd",
  domain = tab_mapa$espvida
)

tab_mapa |>
  leaflet::leaflet() |>
  leaflet::addTiles() |>
  leaflet::addPolygons(
    fillColor = ~color_map(espvida),
    color = "black",
    weight = 1,
    fillOpacity = 0.8
  )
```